language: python
python: 3.8

cache: pip

install:
    - pip install -r ./requirements.txt

script:
    - cd ./test
    - python ./common.unittest.py
    - python ./datatype.unittest.py
    - python ./io.unittest.py
    - python ./selection.unittest.py
    - python ./legacy.unittest.py
    - python ./sim.unittest.py
